const GET_TASKS  = 'GET_TASKS '
const GET_TASKS_SUCCESS  = 'GET_TASKS_SUCCESS'
const GET_TASKS_FAIL  = 'GET_TASKS_FAIL'
const SET_SORT_ORDER = 'SET_SORT_ORDER'
const SET_PAGE_LIMIT = 'SET_PAGE_LIMIT'
const SET_UPDATE_MODE = 'SET_UPDATE_MODE'
const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS'

export {
    GET_TASKS ,
    GET_TASKS_SUCCESS ,
    GET_TASKS_FAIL ,
    SET_SORT_ORDER,
    SET_PAGE_LIMIT,
    SET_UPDATE_MODE,
    SET_SEARCH_PARAMS
}