const TASKS_REQUEST = 'TASKS_REQUEST'
const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
const REQUEST_FAILURE = 'REQUEST_FAILURE'
const SET_SORT_ORDER = 'SET_SORT_ORDER'
const SET_PAGE_LIMIT = 'SET_PAGE_LIMIT'
const SET_UPDATE_MODE = 'SET_UPDATE_MODE'
const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS'

export {
    TASKS_REQUEST,
    REQUEST_SUCCESS,
    REQUEST_FAILURE,
    SET_SORT_ORDER,
    SET_PAGE_LIMIT,
    SET_UPDATE_MODE,
    SET_SEARCH_PARAMS
}